# frozen_string_literal: true

module NattyUI::Ansi
  # @!parse CURSOR_SHOW = …
  CURSOR_SHOW = "\e[?25h"
  # @!parse CURSOR_HIDE = …
  CURSOR_HIDE = "\e[?25l"

  # @!parse CURSOR_HOME = …
  CURSOR_HOME = cursor_pos(nil, nil)
  # @!parse CURSOR_FIRST_ROW = …
  CURSOR_FIRST_ROW = cursor_pos(1).freeze
  # @!parse CURSOR_FIRST_COLUMN = …
  CURSOR_FIRST_COLUMN = cursor_column(1).freeze

  # @!parse CURSOR_SAFE_POS_SCO = …
  CURSOR_SAFE_POS_SCO = "\e[s"
  # @!parse CURSOR_SAFE_POS_DEC = …
  CURSOR_SAFE_POS_DEC = "\e7"
  CURSOR_SAFE_POS = CURSOR_SAFE_POS_DEC

  # @!parse CURSOR_RESTORE_POS_SCO = …
  CURSOR_RESTORE_POS_SCO = "\e[u"
  # @!parse CURSOR_RESTORE_POS_DEC = …
  CURSOR_RESTORE_POS_DEC = "\e8"
  CURSOR_RESTORE_POS = CURSOR_RESTORE_POS_DEC

  # @!parse SCREEN_ERASE = …
  SCREEN_ERASE = screen_erase(:entire)

  # @!parse SCREEN_SAVE = …
  SCREEN_SAVE = "\e[?47h"
  # @!parse SCREEN_RESTORE = …
  SCREEN_RESTORE = "\e[?47l"

  # @!parse SCREEN_ALTERNATE = …
  SCREEN_ALTERNATE = "\e[?1049h"
  # @!parse SCREEN_ALTERNATE_OFF = …
  SCREEN_ALTERNATE_OFF = "\e[?1049l"

  # @!parse LINE_PREVIOUS = …
  LINE_PREVIOUS = cursor_previous_line(1).freeze
  # @!parse LINE_NEXT = …
  LINE_NEXT = cursor_next_line(1).freeze
  # @!parse LINE_ERASE = …
  LINE_ERASE = line_erase(:entire)

  # @!parse RESET = …
  RESET = self[:reset].freeze

  # @!parse BOLD = …
  BOLD = self[:bold].freeze
  # @!parse BOLD_OFF = …
  BOLD_OFF = self[:bold].freeze

  # @!parse FAINT = …
  FAINT = self[:faint].freeze
  # @!parse FAINT_OFF = …
  FAINT_OFF = self[:faint_off].freeze

  # @!parse ITALIC = …
  ITALIC = self[:italic].freeze
  # @!parse ITALIC_OFF = …
  ITALIC_OFF = self[:italic_off].freeze

  # @!parse STRIKE = …
  STRIKE = self[:strike].freeze
  # @!parse STRIKE_OFF = …
  STRIKE_OFF = self[:strike_off].freeze

  # @!parse UNDERLINE = …
  UNDERLINE = self[:underline].freeze
  # @!parse DOUBLE_UNDERLINE = …
  DOUBLE_UNDERLINE = self[:double_underline].freeze
  # @!parse UNDERLINE_OFF = …
  UNDERLINE_OFF = self[:underline_off].freeze

  # @!parse CURLY_UNDERLINE = …
  CURLY_UNDERLINE = self[:curly_underline].freeze
  # @!parse CURLY_UNDERLINE_OFF = …
  CURLY_UNDERLINE_OFF = self[:curly_underline_off].freeze

  # @!parse BLINK = …
  BLINK = self[:blink].freeze
  # @!parse BLINK_OFF = …
  BLINK_OFF = self[:blink_off].freeze

  # @!parse INVERT = …
  INVERT = self[:invert].freeze
  # @!parse INVERT_OFF = …
  INVERT_OFF = self[:invert_off].freeze

  # @!parse HIDE = …
  HIDE = self[:hide].freeze
  # @!parse REVEAL = …
  REVEAL = self[:reveal].freeze

  # @!visibility private
  CLS = "#{CURSOR_HOME}#{SCREEN_ERASE}".freeze

  # @!visibility private
  CLL = "#{CURSOR_FIRST_COLUMN}#{LINE_ERASE}".freeze

  # @!visibility private
  FRAME_COLOR = self[39].freeze

  # @!visibility private
  SCREEN_BLANK =
    "#{CURSOR_SAFE_POS}#{
      SCREEN_ALTERNATE
    }#{CURSOR_HOME}#{SCREEN_ERASE}#{RESET}".freeze

  # @!visibility private
  SCREEN_UNBLANK = "#{RESET}#{SCREEN_ALTERNATE_OFF}#{CURSOR_RESTORE_POS}".freeze
end
